# syntax = docker/dockerfile:1

# This Dockerfile is designed for production, not development. Use with Kamal or build'n'run by hand:
# docker build -t my-app .
# docker run -d -p 80:80 -p 443:443 --name my-app -e RAILS_MASTER_KEY=<value from config/master.key> my-app

# Make sure RUBY_VERSION matches the Ruby version in .ruby-version
FROM ruby:3.2.2

RUN apt-get update -qq && apt-get install -y \
    build-essential \
    nodejs \
    npm \
    postgresql-client

# 最新版の Yarn をインストール
RUN npm install -g yarn@latest

# 作業ディレクトリを設定
WORKDIR /muscle_recipe

# Gemfile をコピーして依存関係をインストール
COPY Gemfile Gemfile.lock ./
RUN gem install bundler && bundle install

# package.json と yarn.lock をコピー
COPY package.json yarn.lock ./
RUN yarn install --pure-lockfile
RUN yarn add preline

# フロントエンドのビルド
RUN yarn build

# アプリケーションコードをコピー
COPY . .

# サーバー起動
CMD ["rails", "server", "-b", "0.0.0.0"]